package injection;

import org.objectweb.asm.Opcodes;
import org.objectweb.asm.tree.AbstractInsnNode;
import org.objectweb.asm.tree.ClassNode;
import org.objectweb.asm.tree.FieldInsnNode;
import org.objectweb.asm.tree.InsnList;
import org.objectweb.asm.tree.InsnNode;
import org.objectweb.asm.tree.IntInsnNode;
import org.objectweb.asm.tree.JumpInsnNode;
import org.objectweb.asm.tree.LabelNode;
import org.objectweb.asm.tree.MethodNode;
import org.objectweb.asm.tree.TypeInsnNode;
import org.objectweb.asm.tree.VarInsnNode;

/**
 * Native Loader Injection
 *
 * The pack200-compressed 508 HD client's class {@code f} (originally Class43)
 * implements a command dispatch loop in its {@code run()} method. The dispatch
 * handles commands {1, 2, 4, 8, 9} but is missing command 10 (DLL loading).
 * When command 10 arrives the dispatcher falls through to {@code throw new
 * Exception()}, which causes the catch block to set {@code dl.f = 2} (error),
 * and the client never initialises its 3D rendering libraries.
 *
 * <p>This injection splices a command-10 check immediately before the
 * {@code throw new Exception()} sequence. The handler is intentionally a
 * no-op: it simply jumps to the existing success path where {@code dl.f = 1}
 * is assigned. Boot.class (generated by {@link NativeLibraryBundler}) is
 * responsible for pre-loading the native DLLs before the client starts, so
 * the client never actually needs to load them itself.
 *
 * <p>Pattern searched for (the "throw" sentinel):
 * <pre>
 *   NEW java/lang/Exception
 *   DUP
 *   INVOKESPECIAL java/lang/Exception.&lt;init&gt;:()V
 *   ATHROW
 * </pre>
 *
 * <p>Pattern searched for (the success target):
 * <pre>
 *   ICONST_1
 *   PUTFIELD &lt;someClass&gt;.&lt;someField&gt;:I
 * </pre>
 *
 * <p>Injected sequence (inserted immediately before the NEW Exception):
 * <pre>
 *   BIPUSH 10
 *   ILOAD_2          // i = the dispatched command number
 *   IF_ICMPNE  throwLabel   // if i != 10 fall through to original throw
 *   GOTO       successLabel // i == 10 → jump to dl.f = 1 success path
 * throwLabel:
 *   // original: NEW java/lang/Exception; DUP; INVOKESPECIAL; ATHROW
 * </pre>
 */
public final class NativeLoaderInjection {

    private NativeLoaderInjection() {
    }

    /**
     * Applies the command-10 no-op handler to the matching class in the context.
     *
     * @return 1 if the patch was applied, 0 otherwise
     */
    public static int apply(InjectionContext ctx) {
        System.out.println("[NativeLoader] Scanning for Class43 run() command dispatcher...");

        for (ClassNode classNode : ctx.classes.values()) {
            if (!implementsRunnable(classNode)) continue;
            if (!hasField(classNode, "Ljava/io/File;")) continue;

            for (Object m : classNode.methods) {
                MethodNode method = (MethodNode) m;
                if (!"run".equals(method.name) || !"()V".equals(method.desc)) continue;

                System.out.println("[NativeLoader] Candidate: " + classNode.name + ".run()");

                if (patchMethod(classNode, method)) {
                    ctx.markDirty(classNode.name);
                    System.out.println("[NativeLoader] Patched command dispatcher in: "
                            + classNode.name + ".run()");
                    return 1;
                }
            }
        }

        System.out.println("[NativeLoader] WARNING: No matching class found — patch NOT applied.");
        return 0;
    }

    // -------------------------------------------------------------------------
    // Patch logic
    // -------------------------------------------------------------------------

    /**
     * Patches the {@code run()} method.
     *
     * <ol>
     *   <li>Locates the {@code throw new Exception()} sentinel (the "unknown command" fallthrough).</li>
     *   <li>Locates the success assignment {@code iconst_1; putfield ...:I}.</li>
     *   <li>Inserts a command-10 guard before the throw: if i==10 goto success, else fall through to throw.</li>
     * </ol>
     */
    private static boolean patchMethod(ClassNode classNode, MethodNode method) {
        // --- Find: NEW java/lang/Exception; DUP; INVOKESPECIAL <init>; ATHROW ---
        AbstractInsnNode throwNew = findThrowNewException(method);
        if (throwNew == null) {
            System.out.println("[NativeLoader]   Could not find 'throw new Exception()' sentinel.");
            return false;
        }
        System.out.println("[NativeLoader]   Found throw-new-Exception sentinel.");

        // --- Find: ICONST_1; PUTFIELD ...:I  (the dl.f = 1 success assignment) ---
        AbstractInsnNode successIconst1 = findSuccessAssignment(method);
        if (successIconst1 == null) {
            System.out.println("[NativeLoader]   Could not find 'dl.f = 1' success assignment.");
            return false;
        }
        System.out.println("[NativeLoader]   Found success assignment (dl.f = 1).");

        // --- Determine the iload slot for the command variable ---
        // The dispatch pattern is: istore_N ... bipush 9; iload_N; if_icmpne ...
        // We find iload_N by scanning backwards from throwNew for an IF_ICMPNE
        // whose previous real instruction is an ILOAD.
        int commandSlot = findCommandVarSlot(throwNew);
        if (commandSlot < 0) {
            // Hard-coded fallback: slot 2 is the conventional slot in the 508 client.
            commandSlot = 2;
            System.out.println("[NativeLoader]   Could not detect command var slot, defaulting to 2.");
        } else {
            System.out.println("[NativeLoader]   Command var slot: " + commandSlot);
        }

        // --- Build the injection sequence ---
        //
        //   BIPUSH 10
        //   ILOAD  commandSlot
        //   IF_ICMPNE  lblThrow        ← not command 10: fall through to original throw
        //   GOTO       lblSuccess      ← command 10: skip to dl.f = 1
        // lblThrow:
        //   <original NEW Exception ...>
        //
        // We also need lblSuccess to point at successIconst1.  We attach it as a
        // LabelNode just before that instruction so ASM resolves it correctly.

        LabelNode lblThrow   = new LabelNode();
        LabelNode lblSuccess = new LabelNode();

        // Anchor lblSuccess immediately before the ICONST_1 success instruction.
        method.instructions.insertBefore(successIconst1, lblSuccess);

        // Build the guard block.
        InsnList guard = new InsnList();
        guard.add(new IntInsnNode(Opcodes.BIPUSH, 10));
        guard.add(new VarInsnNode(Opcodes.ILOAD, commandSlot));
        guard.add(new JumpInsnNode(Opcodes.IF_ICMPNE, lblThrow));  // i != 10 → throw
        guard.add(new JumpInsnNode(Opcodes.GOTO, lblSuccess));      // i == 10 → success
        guard.add(lblThrow);                                         // label before existing throw

        // Insert the guard immediately before the throw sentinel.
        method.instructions.insertBefore(throwNew, guard);

        return true;
    }

    // -------------------------------------------------------------------------
    // Pattern finders
    // -------------------------------------------------------------------------

    /**
     * Scans the method for the sequence:
     * <pre>NEW java/lang/Exception; DUP; INVOKESPECIAL java/lang/Exception.&lt;init&gt;; ATHROW</pre>
     * Returns the {@code NEW} node, or {@code null} if not found.
     */
    private static AbstractInsnNode findThrowNewException(MethodNode method) {
        AbstractInsnNode insn = method.instructions.getFirst();
        while (insn != null) {
            if (insn.getOpcode() == Opcodes.NEW && insn instanceof TypeInsnNode) {
                TypeInsnNode typeInsn = (TypeInsnNode) insn;
                if (!"java/lang/Exception".equals(typeInsn.desc)) {
                    insn = insn.getNext();
                    continue;
                }

                // Verify: DUP follows
                AbstractInsnNode n1 = realNext(insn);
                if (n1 == null || n1.getOpcode() != Opcodes.DUP) {
                    insn = insn.getNext();
                    continue;
                }

                // Verify: INVOKESPECIAL Exception.<init> follows
                AbstractInsnNode n2 = realNext(n1);
                if (n2 == null || n2.getOpcode() != Opcodes.INVOKESPECIAL) {
                    insn = insn.getNext();
                    continue;
                }
                org.objectweb.asm.tree.MethodInsnNode initCall =
                        (org.objectweb.asm.tree.MethodInsnNode) n2;
                if (!"java/lang/Exception".equals(initCall.owner)
                        || !"<init>".equals(initCall.name)) {
                    insn = insn.getNext();
                    continue;
                }

                // Verify: ATHROW follows
                AbstractInsnNode n3 = realNext(n2);
                if (n3 == null || n3.getOpcode() != Opcodes.ATHROW) {
                    insn = insn.getNext();
                    continue;
                }

                return insn; // Found — return the NEW node
            }
            insn = insn.getNext();
        }
        return null;
    }

    /**
     * Scans the method for the first occurrence of:
     * <pre>ALOAD_1; ICONST_1; PUTFIELD &lt;owner&gt;.&lt;name&gt;:I</pre>
     * which corresponds to {@code class31.anInt529 = 1} (success assignment).
     * Returns the {@code ALOAD_1} node (not ICONST_1) so the GOTO target
     * includes the object reference push, keeping the stack consistent.
     */
    private static AbstractInsnNode findSuccessAssignment(MethodNode method) {
        AbstractInsnNode insn = method.instructions.getFirst();
        while (insn != null) {
            if (insn.getOpcode() == Opcodes.ICONST_1) {
                AbstractInsnNode next = realNext(insn);
                if (next instanceof FieldInsnNode
                        && next.getOpcode() == Opcodes.PUTFIELD
                        && "I".equals(((FieldInsnNode) next).desc)) {
                    // Return the ALOAD before ICONST_1 (pushes the object ref)
                    AbstractInsnNode prev = realPrev(insn);
                    if (prev != null && prev.getOpcode() == Opcodes.ALOAD) {
                        return prev;
                    }
                    return insn; // fallback
                }
            }
            insn = insn.getNext();
        }
        return null;
    }

    /**
     * Heuristic: scans backwards from the throw-sentinel looking for an
     * {@code IF_ICMPNE} whose immediately preceding real instruction is an
     * {@code ILOAD}. Returns that slot number, or {@code -1} if not found.
     *
     * <p>This identifies the local variable that holds the dispatched command
     * number (e.g. {@code iload_2} in the bipush-9 / iload-2 / if_icmpne chain).
     */
    private static int findCommandVarSlot(AbstractInsnNode throwNew) {
        AbstractInsnNode scan = throwNew.getPrevious();
        int steps = 0;

        while (scan != null && steps < 40) {
            if (scan.getOpcode() == Opcodes.IF_ICMPNE) {
                AbstractInsnNode prev = realPrev(scan);
                if (prev instanceof VarInsnNode
                        && prev.getOpcode() == Opcodes.ILOAD) {
                    return ((VarInsnNode) prev).var;
                }
            }
            steps++;
            scan = scan.getPrevious();
        }
        return -1;
    }

    // -------------------------------------------------------------------------
    // Helpers shared with DllDebugInjection (duplicated to keep files independent)
    // -------------------------------------------------------------------------

    private static AbstractInsnNode realNext(AbstractInsnNode n) {
        n = n.getNext();
        while (n != null && n.getOpcode() == -1) n = n.getNext();
        return n;
    }

    private static AbstractInsnNode realPrev(AbstractInsnNode n) {
        n = n.getPrevious();
        while (n != null && n.getOpcode() == -1) n = n.getPrevious();
        return n;
    }

    private static boolean implementsRunnable(ClassNode node) {
        if (node.interfaces == null) return false;
        for (Object iface : node.interfaces) {
            if ("java/lang/Runnable".equals(iface)) return true;
        }
        return false;
    }

    private static boolean hasField(ClassNode node, String desc) {
        for (Object f : node.fields) {
            org.objectweb.asm.tree.FieldNode field = (org.objectweb.asm.tree.FieldNode) f;
            if (desc.equals(field.desc)) return true;
        }
        return false;
    }
}
